[package]
name = "user-registration-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
jsonwebtoken = "10.3.0"
serde = "1.0.228"
serde_derive = "1.0.228"
tokio = "1.49.0"

[dev-dependencies]
tokio-test = "0.4.5"
